### ISSUE TITLE
E119: Not enough arguments for function: sy#repo#get_diff_git

### ISSUE THREAD

**Issue by chocoelho** [mhinz/vim-signify#213]
While using vim-signify (if I remove the package the message is gone), I receive the following every time I open a new file:

```
Error detected while processing function sy#start..sy#repo#detected..sy#repo#get_diff_start:
line 46:
E119: Not enough arguments for function: sy#repo#get_diff_git
```

I've done some search but still I'm not sure if this is related to this package or to git itself.

**Comment by mhinz** [comment]
Can you update vim-signify? I think the bug you describe was fixed 8 hours ago.

**Comment by chocoelho** [comment]
Still happening, but using Neovim it gives more info about it:

```
Error detected while processing function sy#start[39]..sy#repo#detect[13]..sy#repo#get_diff_start[10]..<SNR>96_initialize_job:                         
line    2:                                                                                                                                             
E706: Variable type mismatch for: cmd                                                                                                                  
Error detected while processing function sy#start[39]..sy#repo#detect[13]..sy#repo#get_diff_start:                                                     
line   10:                                                                                                                                             
E714: List required 
```

**Comment by mhinz** [comment]
Are you using Windows?

**Comment by chocoelho** [comment]
1. NVim 0.1.4 || Vim 7.4 (Vim stopped the messages now, don't really know why, but they are still active in NVim)
2. git
3. see below

```Messages maintainer: Bram Moolenaar <Bram@vim.org>                                                                                                     
E32: No file name                                                                                                                                      
E32: No file name                                                                                                                                      
"tsconfig.json" [noeol] 26L, 465C                                                                                                                      
Error detected while processing function sy#start[39]..sy#repo#detect[13]..sy#repo#get_diff_start[10]..<SNR>96_initialize_job:                         
line    2:                                                                                                                                             
E706: Variable type mismatch for: cmd                                                                                                                  
Error detected while processing function sy#start[39]..sy#repo#detect[13]..sy#repo#get_diff_start:                                                     
line   10:                                                                                                                                             
E714: List required                                                                                                                                    
"tsconfig.json" 26L, 466C written                                                                                                                      
[sy] No VCS found. Disabling.                                                                                                                          
"tsconfig.json" 26L, 466C written                                                                                                                      
[sy] Inactive buffer.                                                                                                                                  
"package.json" 45L, 1271C                                                                                                                              
Error detected while processing function sy#start[39]..sy#repo#detect[13]..sy#repo#get_diff_start[10]..<SNR>96_initialize_job:                         
line    2:                                                                                                                                             
E706: Variable type mismatch for: cmd                                                                                                                  
Error detected while processing function sy#start[39]..sy#repo#detect[13]..sy#repo#get_diff_start:                                                     
line   10:                                                                                                                                             
E714: List required                                                                                                                                    
```

**Comment by mhinz** [comment]
Well, Neovim 0.1.4 is quite old already. Could you please update it to the latest release 0.1.7 (which is also a few months old already)?

**Comment by chocoelho** [comment]
You're right! It was due to this old version, updated from a editor-specific repository for my package manager and it's gone. Thanks.
